### ISSUE TITLE
Add a follow-up when the ticket is resolved

### ISSUE THREAD

**Issue by TheDevilDan** [tomolimo/mailanalyzer#58]
Hello,
First of all your plug-in is great!
It adds a follow-up to the tickets following the answers of the users who keep the email address of glpi in CC.

Is it possible that this behavior also works when the ticket is in resolved status? Or even closed?

Is this configurable or is it not provided for natively? Because when a ticket is solved, it creates a new ticket, and I have to merge the new ticket with the solved ticket, it works with the solved ticket, but not with a closed ticket. (With GLPI Natively merge ticket)

**Comment by tomolimo** [comment]
Hello @TheDevilDan 
I understand your needs, but they are opposite to the GLPI default behavior about solved and closed tickets...
So I will not add this feature to this plugin.
Sorry for that,
Thank you
Regards,
Tomolimo

**Comment by TheDevilDan** [comment]
Bonjour, pourtant dans GLPI, lorsqu'un utilisateur répond à un ticket résolu par mail (notification mail) le ticket se ré-ouvre correctement, et ajoute un suivi, ça serait parfait si dans le cas ou l'utilisateur réponds avec helpdesk en copie cela fasse pareil (car il n'aurait pas répondu normalement via la notification) c'est un comportement par défaut de GLPI pourtant ?

**Comment by tomolimo** [comment]
Hello @TheDevilDan 
After some look into the source code, I can see a test ....
I'll check and keep you informed
Thank you
Regards
Tomolimo

**Comment by tomolimo** [comment]
Hello @TheDevilDan 

Here are the results of the digging in the history of the chages in GLPI in the mailcollector.class.php and in the mailanalyzer/hook.php:

1. in GLPI only the close ticket can't receive new followup by email, and a new ticket is created when referenced ticket is closed.
2. in mailanalyzer solve and close tickets can't receive new followup by email, and a new ticket is created when referenced ticket is solved/closed

I'll keep you informed about an harmonized solution about this.

Thank you
Regards,
Tomolimo

**Comment by TheDevilDan** [comment]
Thank you very much, this behaviour would be great and would allow to have follow-ups when a ticket is solved and it reopens it as GLPI does by default.

**Comment by TheDevilDan** [comment]
Hi ! If I want to custom for me only the plugin, can I change this line only from hook file ?
Before :
if ($locTicket->fields['status'] !=  CommonITILObject::SOLVED && $locTicket->fields['status'] != CommonITILObject::CLOSED) {
After :
if ($locTicket->fields['status'] != CommonITILObject::CLOSED) {

**Comment by tomolimo** [comment]
Hello @TheDevilDan 
Yes, you may do so.
This is what I'm going to do :)
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @TheDevilDan 
Fixed by latest release https://github.com/tomolimo/mailanalyzer/releases/tag/2.0.2 
Thank you
Regards,
Tomolimo

**Comment by TheDevilDan** [comment]
Hello thanks for the latest release !
I've just tested it with success!

**Comment by TheDevilDan** [comment]
Thanks again, and just for the record, there's just one little comment that needs updating but it's not important at all:

               // TicketFollowup creation only if ticket status is not solved or closed

Becomes :

               // TicketFollowup creation only if ticket status is not closed

**Comment by tomolimo** [comment]
you are right, than kyou to show this wrong comment :)
